@import 'app/templates/site/plugins/form/js/plugin.js'
@import 'app/templates/site/plugins/owl/js/plugin.js'
@import 'app/templates/site/plugins/seo/js/plugin.js'


@import 'app/templates/site/widgets/modal/js/widget.js'
@import 'app/templates/site/widgets/photoswipe/js/widget.js'

@import 'app/templates/site/modules/header-nav/js/module.js'
@import 'app/templates/site/modules/bunner-slider-1/js/module.js'
@import 'app/templates/site/modules/numbers-items-1/js/module.js'
@import 'app/templates/site/modules/numbers-items-2/js/module.js'
@import 'app/templates/site/modules/advantages-module-2/js/module.js'
@import 'app/templates/site/modules/catalog/js/module.js'
@import 'app/templates/site/modules/catalog-2/js/module.js'
@import 'app/templates/site/modules/catalog-3/js/module.js'
@import 'app/templates/site/modules/present/js/module.js'
@import 'app/templates/site/modules/job-us-section/js/module.js'
@import 'app/templates/site/modules/bunner-slider-2/js/module.js'
@import 'app/templates/site/modules/sertificate/js/module.js'
@import 'app/templates/site/modules/oplata-section/js/module.js'
@import 'app/templates/site/modules/dostavka-section/js/module.js'